// project-a-next/app/jobs/[id]/page.tsx
import JobCard from "@/components/JobCard";
import { getJobById } from "@/services/jobService";

// File-system routing uses the folder name [id]; params are passed as props to the page component.
export default async function JobDetails({ params }: { params: { id: string } }) {
  const jobId = Number(params.id);
  const job = await getJobById(jobId);

  if (!job) {
    return (
      <main className="min-h-screen bg-zinc-50 py-12 text-center text-zinc-700">
        <p className="text-lg font-medium">Job not found</p>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-zinc-50 py-12 text-zinc-900">
      <section className="mx-auto flex max-w-3xl flex-col gap-6 px-6">
        <header className="flex flex-col gap-2">
          <p className="text-sm font-semibold text-emerald-700">JobHunt Tracker</p>
          <h1 className="text-3xl font-bold">{job.title}</h1>
          <p className="text-sm text-zinc-600">{job.company}</p>
        </header>
        <JobCard job={job} />
        <div className="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm">
          <h2 className="text-lg font-semibold text-zinc-900">Description</h2>
          <p className="mt-2 text-sm text-zinc-700 whitespace-pre-line">{job.description}</p>
          <p className="mt-4 text-sm text-zinc-600">Applied: {job.date_applied}</p>
        </div>
      </section>
    </main>
  );
}

// project-b-nuxt/app/pages/jobs/[id].vue
<script setup lang="ts">
import { getJobById } from "~/services/jobService";
import type { Job } from "~/services/jobService";

// File-system routing uses the filename [id].vue; the global route object exposes params for the page.
const route = useRoute();
const jobId = Number(route.params.id);

const job = ref<Job | undefined>();

job.value = await getJobById(jobId);
</script>

<template>
  <main class="min-h-screen bg-zinc-50 py-12 text-zinc-900">
    <section class="mx-auto flex max-w-3xl flex-col gap-6 px-6">
      <header class="flex flex-col gap-2">
        <p class="text-sm font-semibold text-emerald-700">JobHunt Tracker</p>
        <h1 v-if="job" class="text-3xl font-bold">{{ job.title }}</h1>
        <p v-if="job" class="text-sm text-zinc-600">{{ job.company }}</p>
      </header>

      <div v-if="job" class="flex flex-col gap-4">
        <JobCard :job="job" />
        <div class="rounded-xl border border-zinc-200 bg-white p-4 shadow-sm">
          <h2 class="text-lg font-semibold text-zinc-900">Description</h2>
          <p class="mt-2 whitespace-pre-line text-sm text-zinc-700">{{ job.description }}</p>
          <p class="mt-4 text-sm text-zinc-600">Applied: {{ job.date_applied }}</p>
        </div>
      </div>

      <p v-else class="text-center text-lg font-medium text-zinc-700">Job not found</p>
    </section>
  </main>
</template>
